version: '3.1'

services:
  reports_pg:
    image: postgres:latest
    container_name: postgre_reports
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reports
    ports:
      - "5432:5432"
    volumes:
      - reports_pg:/var/lib/postgresql

volumes:
  reports_pg: